# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
script:
- xctool -project SFCoreDataOneWaySynchronization.xcodeproj -scheme SFCoreDataOneWaySynchronization -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -project SFCoreDataOneWaySynchronization.xcodeproj -scheme SFCoreDataOneWaySynchronizationTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
